//
//  BATTINGSUMMARYPushRecord.m
//  CAPScoringApp
//
//  Created by Ramas Mac Book on 7/3/16.
//  Copyright © 2016 agaram. All rights reserved.
//

#import "BATTINGSUMMARYPushRecord.h"

@implementation BATTINGSUMMARYPushRecord
@synthesize COMPETITIONCODE;
@synthesize MATCHCODE;
@synthesize BATTINGTEAMCODE;
@synthesize INNINGSNO;
@synthesize BATTINGPOSITIONNO;
@synthesize BATSMANCODE;
@synthesize RUNS;
@synthesize BALLS;
@synthesize ONES;
@synthesize TWOS;
@synthesize THREES;
@synthesize FOURS;
@synthesize SIXES;
@synthesize DOTBALLS;
@synthesize WICKETNO;
@synthesize WICKETTYPE;
@synthesize FIELDERCODE;
@synthesize BOWLERCODE;
@synthesize WICKETOVERNO;
@synthesize WICKETBALLNO;
@synthesize WICKETSCORE;
@synthesize ISSYNC;


-(NSDictionary *)BATTINGSUMMARYPushRecordDictionary {
    return [NSDictionary dictionaryWithObjectsAndKeys:COMPETITIONCODE,@"COMPETITIONCODE",MATCHCODE,@"MATCHCODE", BATTINGTEAMCODE,@"BATTINGTEAMCODE",INNINGSNO,@"INNINGSNO", BATTINGPOSITIONNO,@"BATTINGPOSITIONNO", INNINGSNO,@"INNINGSNO",BATTINGPOSITIONNO,@"BATTINGPOSITIONNO",BATSMANCODE,@"BATSMANCODE", RUNS,@"RUNS",RUNS,@"RUNS", BALLS,@"BALLS", ONES,@"ONES",TWOS,@"TWOS", THREES,@"THREES", FOURS,@"FOURS", SIXES,@"SIXES", DOTBALLS,@"DOTBALLS", WICKETNO,@"WICKETNO", WICKETTYPE,@"WICKETTYPE", FIELDERCODE,@"FIELDERCODE", BOWLERCODE,@"BOWLERCODE",WICKETOVERNO,@"WICKETOVERNO", WICKETBALLNO,@"WICKETBALLNO", WICKETSCORE,@"WICKETSCORE", ISSYNC,@"ISSYNC", nil];
}

@end
