//
//  InningsEventPushRecord.m
//  CAPScoringApp
//
//  Created by Ramas Mac Book on 7/3/16.
//  Copyright © 2016 agaram. All rights reserved.
//

#import "InningsEventPushRecord.h"

@implementation InningsEventPushRecord

@synthesize COMPETITIONCODE;
@synthesize MATCHCODE;
@synthesize TEAMCODE;
@synthesize INNINGSNO;
@synthesize INNINGSSTARTTIME;
@synthesize INNINGSENDTIME;
@synthesize STRIKERCODE;
@synthesize NONSTRIKERCODE;
@synthesize BOWLERCODE;
@synthesize BATTINGTEAMCODE;
@synthesize CURRENTSTRIKERCODE;
@synthesize CURRENTNONSTRIKERCODE;
@synthesize CURRENTBOWLERCODE;
@synthesize TOTALRUNS;
@synthesize TOTALOVERS;
@synthesize TOTALWICKETS;
@synthesize ISDECLARE;
@synthesize ISFOLLOWON;
@synthesize INNINGSSTATUS;
@synthesize BOWLINGEND;
@synthesize issync;


-(NSDictionary *)InningsEventPushRecordDictionary {
    return [NSDictionary dictionaryWithObjectsAndKeys:COMPETITIONCODE,@"COMPETITIONCODE",MATCHCODE,@"MATCHCODE", TEAMCODE,@"TEAMCODE",INNINGSNO,@"INNINGSNO", INNINGSSTARTTIME,@"INNINGSSTARTTIME", INNINGSENDTIME,@"INNINGSENDTIME",STRIKERCODE,@"STRIKERCODE",NONSTRIKERCODE,@"NONSTRIKERCODE", BOWLERCODE,@"BOWLERCODE",BATTINGTEAMCODE,@"BATTINGTEAMCODE", CURRENTSTRIKERCODE,@"CURRENTSTRIKERCODE", CURRENTNONSTRIKERCODE,@"CURRENTNONSTRIKERCODE",CURRENTBOWLERCODE,@"CURRENTBOWLERCODE", TOTALRUNS,@"TOTALRUNS", TOTALOVERS,@"TOTALOVERS", TOTALWICKETS,@"TOTALWICKETS", ISDECLARE,@"ISDECLARE", ISFOLLOWON,@"ISFOLLOWON", INNINGSSTATUS,@"INNINGSSTATUS", BOWLINGEND,@"BOWLINGEND", issync,@"issync", nil];
}


@end
